# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Database": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://bwolfson97.github.io/reflection_prompts/"

git_url = "https://github.com/bwolfson97/reflection_prompts/tree/main/"

def custom_doc_links(name): return None
