# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['Database']

# Cell
from fastcore.all import *

# Cell
class Database:
    def __init__(self, path: str):
        self.path = Path(path).expanduser()
        self.load()

    def load(self):
        try: self.db = self.path.read_json()
        except FileNotFoundError: self.db = {}